name: Test and Build Backend
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request_target:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
    branches:
      - 'main'
      - 'v*'
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'backend/go.mod'
          check-latest: true
          cache-dependency-path: backend/go.sum   
      - name: Install Dependencies
        run: |
          cd backend
          go mod download
          go env          
      - name: Test
        run: |
          cd backend
          go test ./...
  build:
    name: build & push
    runs-on: ubuntu-latest
    needs: test
    if: |
      github.event_name == 'pull_request_target'
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up QEMIU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/search-scraper-backend:latest