name: Test and Build Frontrnend
on:
  push:
    paths:
      - 'frontrend/**'
      - '.github/workflows/frontend.yml'
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: yarn
      - name: Test
        run: yarn run test
  build:
    name: build & push
    runs-on: ubuntu-latest
    needs: test
    if: |
        github.ref == 'refs/heads/main' || github.ref == 'refs/heads/v2'
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up QEMIU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/search-scraper-frontend:latest